env:
  browser: true
  es2021: true
  webextensions: true
extends:
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2015
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {}
